server:
  port: 8081
spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:"
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:14.5:///postgres
  cloud:
    stream:
      bindings:
        output:
          content-type: application/json