server:
  port: 8082
spring:
  application:
    name: notifications-service
  config:
    import: "optional:configserver:"
  cloud:
    stream:
      bindings:
        updatedEventConsumer-in-0:
          destination: user-topic
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:mysql:8.0.31:///notification
  cloud:
    stream:
      bindings:
        output:
          content-type: application/json