server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: test
    password: test
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}