server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=user
    username: user
    password: postgres
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}